"use strict";

var XML = 

  '<?xml version="1.0" encoding="UTF-8"?>\n'
+ '<plugin>\n'
  + '<name>%%APP_NAME%%</name>\n'
  + '<folder>%%APP_FOLDER%%</folder>\n'
  + '<iconfilename>icon.png</iconfilename>\n'
  + '<imagefilename>help.png</imagefilename>\n'
  + '<launcher>jsapps/publishing</launcher>\n'
  + '<link>%%APP_LINK%%</link>\n'
  + '<params>sharedLinkMode=1</params>\n'
  + '<activated>1</activated>\n'
  + '<beta>1</beta>\n'
  + '<statstag>slideshow</statstag>\n'
  + '<excludecustomergroups></excludecustomergroups>\n'
  + '<searchable>1</searchable>\n'
  + '<allow_2do>1</allow_2do>\n'
  + '<mainsubject>other</mainsubject>\n'
  + '<allowguest>1</allowguest>\n'
  + '<languages>\n'
    + '<en_gb>\n'
      + '<title>%%APP_TITLE%%</title>\n'
      + '<description></description>\n'
      + '<keywords></keywords>\n'
      + '<yeargroups></yeargroups>\n'
      + '<subjects>hi</subjects>\n'
      + '<apppath/>\n'
      + '<activityname/>\n'
      + '<presentation/>\n'
      + '<iconfilename>icon.png</iconfilename>\n'
      + '<imagefilename>help.png</imagefilename>\n'
      + '<largeiconimage/>\n'
    + '</en_gb>\n'
  + '</languages>\n'
  + '<bundles>Package A</bundles>\n'
  + '<imagemarkers>[]</imagemarkers>\n'
+ '</plugin>'

module.exports = XML;